# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_type',
            field=models.FileField(upload_to=b''),
        ),
    ]
